package main

import (
	"github.com/kibana-http-apis/mcp-server/config"
	"github.com/kibana-http-apis/mcp-server/models"
	tools_elastic_agent_policies "github.com/kibana-http-apis/mcp-server/tools/elastic_agent_policies"
	tools_elastic_agent_actions "github.com/kibana-http-apis/mcp-server/tools/elastic_agent_actions"
	tools_roles "github.com/kibana-http-apis/mcp-server/tools/roles"
	tools_elastic_package_manager_epm "github.com/kibana-http-apis/mcp-server/tools/elastic_package_manager_epm"
	tools_alerting "github.com/kibana-http-apis/mcp-server/tools/alerting"
	tools_maintenance_window "github.com/kibana-http-apis/mcp-server/tools/maintenance_window"
	tools_fleet_enrollment_api_keys "github.com/kibana-http-apis/mcp-server/tools/fleet_enrollment_api_keys"
	tools_fleet_package_policies "github.com/kibana-http-apis/mcp-server/tools/fleet_package_policies"
	tools_elastic_agents "github.com/kibana-http-apis/mcp-server/tools/elastic_agents"
	tools_fleet_uninstall_tokens "github.com/kibana-http-apis/mcp-server/tools/fleet_uninstall_tokens"
	tools_connectors "github.com/kibana-http-apis/mcp-server/tools/connectors"
	tools_streams "github.com/kibana-http-apis/mcp-server/tools/streams"
	tools_fleet_server_hosts "github.com/kibana-http-apis/mcp-server/tools/fleet_server_hosts"
	tools_elastic_agent_status "github.com/kibana-http-apis/mcp-server/tools/elastic_agent_status"
	tools_ccr_remote_synced_integrations "github.com/kibana-http-apis/mcp-server/tools/ccr_remote_synced_integrations"
	tools_fleet_proxies "github.com/kibana-http-apis/mcp-server/tools/fleet_proxies"
	tools_fleet_internals "github.com/kibana-http-apis/mcp-server/tools/fleet_internals"
	tools_fleet_outputs "github.com/kibana-http-apis/mcp-server/tools/fleet_outputs"
	tools_elastic_agent_binary_download_sources "github.com/kibana-http-apis/mcp-server/tools/elastic_agent_binary_download_sources"
	tools_api "github.com/kibana-http-apis/mcp-server/tools/api"
	tools_data_streams "github.com/kibana-http-apis/mcp-server/tools/data_streams"
	tools_system "github.com/kibana-http-apis/mcp-server/tools/system"
	tools_message_signing_service "github.com/kibana-http-apis/mcp-server/tools/message_signing_service"
	tools_spaces "github.com/kibana-http-apis/mcp-server/tools/spaces"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_elastic_agent_policies.CreateGet_fleet_kubernetes_downloadTool(cfg),
		tools_elastic_agent_policies.CreateGet_fleet_agent_policies_agentpolicyid_outputsTool(cfg),
		tools_elastic_agent_actions.CreatePost_fleet_agents_agentid_actionsTool(cfg),
		tools_roles.CreateDelete_security_role_nameTool(cfg),
		tools_roles.CreateGet_security_role_nameTool(cfg),
		tools_roles.CreatePut_security_role_nameTool(cfg),
		tools_elastic_agent_policies.CreateGet_fleet_agent_policies_agentpolicyid_auto_upgrade_agents_statusTool(cfg),
		tools_elastic_agent_actions.CreatePost_fleet_agents_bulk_upgradeTool(cfg),
		tools_elastic_package_manager_epm.CreatePost_fleet_epm_packages_bulk_upgradeTool(cfg),
		tools_alerting.CreatePost_alerting_rule_id_disableTool(cfg),
		tools_maintenance_window.CreatePost_maintenance_window_id_archiveTool(cfg),
		tools_elastic_package_manager_epm.CreatePost_fleet_epm_packages_pkgname_pkgversion_transforms_authorizeTool(cfg),
		tools_elastic_agent_actions.CreatePost_fleet_agents_agentid_upgradeTool(cfg),
		tools_maintenance_window.CreateDelete_maintenance_window_idTool(cfg),
		tools_maintenance_window.CreateGet_maintenance_window_idTool(cfg),
		tools_maintenance_window.CreatePatch_maintenance_window_idTool(cfg),
		tools_fleet_enrollment_api_keys.CreateDelete_fleet_enrollment_api_keys_keyidTool(cfg),
		tools_fleet_enrollment_api_keys.CreateGet_fleet_enrollment_api_keys_keyidTool(cfg),
		tools_fleet_package_policies.CreatePost_fleet_package_policies_upgradeTool(cfg),
		tools_elastic_agents.CreateDelete_fleet_agents_agentidTool(cfg),
		tools_elastic_agents.CreateGet_fleet_agents_agentidTool(cfg),
		tools_elastic_agents.CreatePut_fleet_agents_agentidTool(cfg),
		tools_fleet_uninstall_tokens.CreateGet_fleet_uninstall_tokensTool(cfg),
		tools_connectors.CreatePost_actions_connector_id_executeTool(cfg),
		tools_alerting.CreatePost_alerting_rule_id_unmute_allTool(cfg),
		tools_elastic_agent_actions.CreateGet_fleet_agents_action_statusTool(cfg),
		tools_elastic_package_manager_epm.CreateGet_fleet_epm_packages_pkgname_pkgversion_filepathTool(cfg),
		tools_streams.CreatePost_streams_disableTool(cfg),
		tools_fleet_server_hosts.CreateDelete_fleet_fleet_server_hosts_itemidTool(cfg),
		tools_fleet_server_hosts.CreateGet_fleet_fleet_server_hosts_itemidTool(cfg),
		tools_fleet_server_hosts.CreatePut_fleet_fleet_server_hosts_itemidTool(cfg),
		tools_elastic_agents.CreateGet_fleet_agents_tagsTool(cfg),
		tools_elastic_agent_actions.CreatePost_fleet_agents_agentid_request_diagnosticsTool(cfg),
		tools_elastic_agent_status.CreateGet_fleet_agent_statusTool(cfg),
		tools_elastic_agent_policies.CreateGet_fleet_agent_policies_agentpolicyid_downloadTool(cfg),
		tools_fleet_package_policies.CreatePost_fleet_package_policies_bulk_getTool(cfg),
		tools_ccr_remote_synced_integrations.CreateGet_fleet_remote_synced_integrations_statusTool(cfg),
		tools_alerting.CreateGet_alerting_rules_findTool(cfg),
		tools_elastic_agent_policies.CreatePost_fleet_agent_policies_outputsTool(cfg),
		tools_fleet_proxies.CreateDelete_fleet_proxies_itemidTool(cfg),
		tools_fleet_proxies.CreateGet_fleet_proxies_itemidTool(cfg),
		tools_fleet_proxies.CreatePut_fleet_proxies_itemidTool(cfg),
		tools_fleet_internals.CreateGet_fleet_settingsTool(cfg),
		tools_fleet_internals.CreatePut_fleet_settingsTool(cfg),
		tools_fleet_uninstall_tokens.CreateGet_fleet_uninstall_tokens_uninstalltokenidTool(cfg),
		tools_fleet_outputs.CreatePost_fleet_logstash_api_keysTool(cfg),
		tools_elastic_package_manager_epm.CreateGet_fleet_epm_packages_bulk_upgrade_taskidTool(cfg),
		tools_elastic_agent_actions.CreatePost_fleet_agents_bulk_update_agent_tagsTool(cfg),
		tools_fleet_enrollment_api_keys.CreatePost_fleet_enrollment_api_keysTool(cfg),
		tools_fleet_enrollment_api_keys.CreateGet_fleet_enrollment_api_keysTool(cfg),
		tools_elastic_agents.CreateGet_fleet_agents_setupTool(cfg),
		tools_elastic_agents.CreatePost_fleet_agents_setupTool(cfg),
		tools_alerting.CreateDelete_alerting_rule_ruleid_snooze_schedule_scheduleidTool(cfg),
		tools_elastic_package_manager_epm.CreateGet_fleet_epm_templates_pkgname_pkgversion_inputsTool(cfg),
		tools_elastic_package_manager_epm.CreatePost_fleet_epm_custom_integrationsTool(cfg),
		tools_elastic_agent_binary_download_sources.CreatePut_fleet_agent_download_sources_sourceidTool(cfg),
		tools_elastic_agent_binary_download_sources.CreateDelete_fleet_agent_download_sources_sourceidTool(cfg),
		tools_elastic_agent_binary_download_sources.CreateGet_fleet_agent_download_sources_sourceidTool(cfg),
		tools_ccr_remote_synced_integrations.CreateGet_fleet_remote_synced_integrations_outputid_remote_statusTool(cfg),
		tools_elastic_package_manager_epm.CreatePut_fleet_epm_custom_integrations_pkgnameTool(cfg),
		tools_elastic_package_manager_epm.CreateDelete_fleet_epm_packages_pkgname_pkgversionTool(cfg),
		tools_elastic_package_manager_epm.CreateGet_fleet_epm_packages_pkgname_pkgversionTool(cfg),
		tools_elastic_package_manager_epm.CreatePost_fleet_epm_packages_pkgname_pkgversionTool(cfg),
		tools_elastic_package_manager_epm.CreatePut_fleet_epm_packages_pkgname_pkgversionTool(cfg),
		tools_streams.CreatePost_streams_name_content_exportTool(cfg),
		tools_elastic_agent_policies.CreateGet_fleet_kubernetesTool(cfg),
		tools_maintenance_window.CreatePost_maintenance_windowTool(cfg),
		tools_elastic_agent_actions.CreatePost_fleet_agents_bulk_unenrollTool(cfg),
		tools_streams.CreateGet_streams_name_significant_eventsTool(cfg),
		tools_api.CreateGet_fleet_space_settingsTool(cfg),
		tools_api.CreatePut_fleet_space_settingsTool(cfg),
		tools_fleet_package_policies.CreatePost_fleet_package_policies_deleteTool(cfg),
		tools_data_streams.CreateGet_fleet_epm_data_streamsTool(cfg),
		tools_system.CreateGet_statusTool(cfg),
		tools_message_signing_service.CreatePost_fleet_message_signing_service_rotate_key_pairTool(cfg),
		tools_spaces.CreateDelete_spaces_space_idTool(cfg),
		tools_spaces.CreateGet_spaces_space_idTool(cfg),
		tools_spaces.CreatePut_spaces_space_idTool(cfg),
		tools_fleet_outputs.CreateDelete_fleet_outputs_outputidTool(cfg),
		tools_fleet_outputs.CreateGet_fleet_outputs_outputidTool(cfg),
		tools_fleet_outputs.CreatePut_fleet_outputs_outputidTool(cfg),
		tools_fleet_package_policies.CreatePost_fleet_package_policies_upgrade_dryrunTool(cfg),
		tools_elastic_agent_policies.CreateGet_fleet_agent_policies_agentpolicyidTool(cfg),
		tools_elastic_agent_policies.CreatePut_fleet_agent_policies_agentpolicyidTool(cfg),
		tools_streams.CreateGet_streams_name_queriesTool(cfg),
		tools_elastic_agent_policies.CreatePost_fleet_agent_policies_bulk_getTool(cfg),
		tools_fleet_outputs.CreateGet_fleet_outputsTool(cfg),
		tools_fleet_outputs.CreatePost_fleet_outputsTool(cfg),
		tools_alerting.CreatePost_alerting_rule_id_snooze_scheduleTool(cfg),
		tools_fleet_server_hosts.CreateGet_fleet_fleet_server_hostsTool(cfg),
		tools_fleet_server_hosts.CreatePost_fleet_fleet_server_hostsTool(cfg),
		tools_fleet_internals.CreateGet_fleet_check_permissionsTool(cfg),
		tools_streams.CreatePost_streams_name_queries_bulkTool(cfg),
		tools_elastic_package_manager_epm.CreatePost_fleet_epm_bulk_assetsTool(cfg),
		tools_connectors.CreateGet_actions_connector_typesTool(cfg),
		tools_elastic_agent_actions.CreatePost_fleet_agents_bulk_reassignTool(cfg),
		tools_data_streams.CreateGet_fleet_data_streamsTool(cfg),
		tools_spaces.CreatePost_spaces_spaceTool(cfg),
		tools_spaces.CreateGet_spaces_spaceTool(cfg),
		tools_streams.CreateGet_streams_name_significant_events_generateTool(cfg),
		tools_elastic_package_manager_epm.CreatePost_fleet_epm_packages_bulk_uninstallTool(cfg),
		tools_roles.CreateGet_security_roleTool(cfg),
		tools_alerting.CreatePost_alerting_rule_id_enableTool(cfg),
		tools_elastic_agent_actions.CreatePost_fleet_agents_actions_actionid_cancelTool(cfg),
		tools_connectors.CreatePost_actions_connector_idTool(cfg),
		tools_connectors.CreatePut_actions_connector_idTool(cfg),
		tools_connectors.CreateDelete_actions_connector_idTool(cfg),
		tools_connectors.CreateGet_actions_connector_idTool(cfg),
		tools_elastic_agent_binary_download_sources.CreateGet_fleet_agent_download_sourcesTool(cfg),
		tools_elastic_agent_binary_download_sources.CreatePost_fleet_agent_download_sourcesTool(cfg),
		tools_streams.CreateGet_streams_name_groupTool(cfg),
		tools_streams.CreatePut_streams_name_groupTool(cfg),
		tools_elastic_agent_policies.CreatePost_fleet_agent_policies_agentpolicyid_copyTool(cfg),
		tools_elastic_agents.CreateGet_fleet_agents_files_fileid_filenameTool(cfg),
		tools_fleet_package_policies.CreatePost_fleet_package_policiesTool(cfg),
		tools_fleet_package_policies.CreateGet_fleet_package_policiesTool(cfg),
		tools_elastic_package_manager_epm.CreateGet_fleet_epm_packages_bulk_uninstall_taskidTool(cfg),
		tools_elastic_agent_actions.CreatePost_fleet_agents_agentid_reassignTool(cfg),
		tools_elastic_package_manager_epm.CreatePost_fleet_epm_packages_bulkTool(cfg),
		tools_connectors.CreateGet_actions_connectorsTool(cfg),
		tools_streams.CreatePost_streams_name_significant_events_previewTool(cfg),
		tools_streams.CreatePost_streams_name_forkTool(cfg),
		tools_elastic_package_manager_epm.CreateDelete_fleet_epm_packages_pkgname_pkgversion_kibana_assetsTool(cfg),
		tools_elastic_package_manager_epm.CreatePost_fleet_epm_packages_pkgname_pkgversion_kibana_assetsTool(cfg),
		tools_api.CreatePost_security_role_queryTool(cfg),
		tools_streams.CreatePost_streams_enableTool(cfg),
		tools_alerting.CreateGet_alerting_rule_idTool(cfg),
		tools_alerting.CreatePost_alerting_rule_idTool(cfg),
		tools_alerting.CreatePut_alerting_rule_idTool(cfg),
		tools_alerting.CreateDelete_alerting_rule_idTool(cfg),
		tools_maintenance_window.CreatePost_maintenance_window_id_unarchiveTool(cfg),
		tools_roles.CreatePost_security_rolesTool(cfg),
		tools_alerting.CreatePost_alerting_rule_id_update_api_keyTool(cfg),
		tools_elastic_package_manager_epm.CreateGet_fleet_epm_packages_installedTool(cfg),
		tools_streams.CreateDelete_streams_name_dashboards_dashboardidTool(cfg),
		tools_streams.CreatePut_streams_name_dashboards_dashboardidTool(cfg),
		tools_alerting.CreatePost_alerting_rule_id_mute_allTool(cfg),
		tools_fleet_proxies.CreateGet_fleet_proxiesTool(cfg),
		tools_fleet_proxies.CreatePost_fleet_proxiesTool(cfg),
		tools_elastic_agents.CreateGet_fleet_agent_status_dataTool(cfg),
		tools_elastic_agent_policies.CreateGet_fleet_agent_policiesTool(cfg),
		tools_elastic_agent_policies.CreatePost_fleet_agent_policiesTool(cfg),
		tools_streams.CreatePost_streams_name_dashboards_bulkTool(cfg),
		tools_streams.CreateGet_streamsTool(cfg),
		tools_elastic_agent_policies.CreatePost_fleet_agent_policies_deleteTool(cfg),
		tools_elastic_package_manager_epm.CreateGet_fleet_epm_packagesTool(cfg),
		tools_elastic_agent_policies.CreateGet_fleet_agent_policies_agentpolicyid_fullTool(cfg),
		tools_elastic_package_manager_epm.CreateDelete_fleet_epm_packages_pkgname_pkgversion_datastream_assetsTool(cfg),
		tools_elastic_agents.CreateGet_fleet_agents_available_versionsTool(cfg),
		tools_streams.CreateDelete_streams_nameTool(cfg),
		tools_streams.CreateGet_streams_nameTool(cfg),
		tools_streams.CreatePut_streams_nameTool(cfg),
		tools_streams.CreateDelete_streams_name_queries_queryidTool(cfg),
		tools_streams.CreatePut_streams_name_queries_queryidTool(cfg),
		tools_alerting.CreatePost_alerting_rule_rule_id_alert_alert_id_unmuteTool(cfg),
		tools_elastic_agents.CreateGet_fleet_agentsTool(cfg),
		tools_elastic_agents.CreatePost_fleet_agentsTool(cfg),
		tools_streams.CreateGet_streams_name_ingestTool(cfg),
		tools_streams.CreatePut_streams_name_ingestTool(cfg),
		tools_elastic_package_manager_epm.CreateGet_fleet_epm_packages_pkgname_statsTool(cfg),
		tools_fleet_package_policies.CreateDelete_fleet_package_policies_packagepolicyidTool(cfg),
		tools_fleet_package_policies.CreateGet_fleet_package_policies_packagepolicyidTool(cfg),
		tools_fleet_package_policies.CreatePut_fleet_package_policies_packagepolicyidTool(cfg),
		tools_elastic_package_manager_epm.CreateGet_fleet_epm_packages_limitedTool(cfg),
		tools_alerting.CreatePost_alerting_rule_rule_id_alert_alert_id_muteTool(cfg),
		tools_fleet_internals.CreatePost_fleet_setupTool(cfg),
		tools_elastic_package_manager_epm.CreateGet_fleet_epm_verification_key_idTool(cfg),
		tools_elastic_agent_actions.CreatePost_fleet_agents_bulk_request_diagnosticsTool(cfg),
		tools_streams.CreateGet_streams_name_dashboardsTool(cfg),
		tools_fleet_internals.CreatePost_fleet_health_checkTool(cfg),
		tools_streams.CreatePost_streams_resyncTool(cfg),
		tools_elastic_agents.CreateDelete_fleet_agents_files_fileidTool(cfg),
		tools_elastic_agent_actions.CreatePost_fleet_agents_agentid_unenrollTool(cfg),
		tools_elastic_agents.CreateGet_fleet_agents_agentid_uploadsTool(cfg),
		tools_fleet_outputs.CreateGet_fleet_outputs_outputid_healthTool(cfg),
		tools_elastic_package_manager_epm.CreateGet_fleet_epm_categoriesTool(cfg),
	}
}
